
spring:
  datasource:
    url: jdbc:mysql://172.16.201.116:3306/rn
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.kaimadata.rn.domain,cn.kaimadata.rn.query